filebeat:
  image: unifiedstreaming/filebeat-for-docker:7.3.2-logstash
  restart: unless-stopped
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock
  environment:
   - LOGSTASH_HOST=validator-dockers-logstash.logstash.svc.k8s.unified-streaming.com
   - LOGSTASH_PORT=5044
   - SHIPPER_NAME=validator-filebeat
